In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets

from nltk.corpus import brown

import nltk
from nltk.corpus import brown
import numpy as np
from collections import Counter
from collections import defaultdict
from math import log
import time
import math
import gensim
from nltk.corpus import brown
from gensim.models import Word2Vec

In [4]:
size = int(len(brown.tagged_sents(categories='news')) * 0.8)
size
brown_tagged_sents = brown.tagged_sents(categories='news')

Getting data

In [5]:
train_sents = brown_tagged_sents[:size]
test_sents = brown_tagged_sents[size:]

In [6]:
# train_sents[0][1]
token_tag_pair_train=[]
for sentence in train_sents:
#     print(sentence)
    for ttu in sentence:
#         print(ttu)
        token_tag_pair_train.append(ttu)

In [17]:
token_tag_pair_train
tokens,taged = zip(*token_tag_pair_train)

In [132]:
# print(tokens[0],taged[0])

In [34]:
# print(len(tokens))
# print(len(taged))

In [35]:
tagged_list=list(taged)

In [36]:
tagged_list=list(set(tagged_list))

print(len(tagged_list))

206


Word2vec model

In [43]:

sentences_news = brown.sents(categories='news')
# model = gensim.models.Word2Vec(sentences_news, min_count=1)
# model.save('brown_model')
print("Brown corpus model saved.")

Brown corpus model saved.


In [46]:
# sentences[3]
model = gensim.models.Word2Vec.load('brown_model')
# print (model.most_similar('boy'))
# print("#############################################3")
# print (len(model['boy']))

logistic regression

In [110]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def loss(h, y):
    return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()


def logistic(X, y):
         
    # weights initialization
    theta = np.zeros(X.shape[1])

    for i in range(30):
        z = np.dot(X, theta)
        h = sigmoid(z)
        gradient = np.dot(X.T, (h - y)) / y.size
        theta -= 0.1 * gradient

        z = np.dot(X,theta)
        h = sigmoid(z)
        loss_v = loss(h, y)

        if(i%10):
            pass
#             print("loss ",loss_v)


    return theta


creating one vs all label

In [111]:
def set_labels(label):
    X=[]
    Y=[]
    for ttp in token_tag_pair_train:
#         print(t[1])
        if(ttp[1]==label):
#             print(ttp)
            X.append(model[ttp[0]])
            Y.append(1);
        else:
#             X.append(ttp[0])
            X.append(model[ttp[0]])
            Y.append(0);
    
    return X,Y

In [112]:




# X,Y=set_labels("DT")

# print(len(X))
# print(len(Y))

# i=0
# for t in tagged_list:
    
#     print(i,t)
#     i+=1

/home/sathis/.local/lib/python3.5/site-packages/ipykernel_launcher.py:12: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if sys.path[0] == '':
/home/sathis/.local/lib/python3.5/site-packages/ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


79795
79795


In [113]:
# X[0]

In [114]:

X = np.asarray(X)
Y = np.asarray(Y)
m1=logistic(X,Y)
# X

In [115]:
X = np.asarray(X)

In [116]:
m1

array([-0.0143281 , -0.14216931, -0.13082532,  0.07674743,  0.03751024,
       -0.0192537 ,  0.10530969,  0.02299568,  0.0332903 , -0.06239861,
       -0.02775893, -0.01707777, -0.00593955, -0.06310597, -0.07461621,
       -0.12237411, -0.1696348 , -0.03629353,  0.02409271,  0.02938129,
        0.03914128, -0.13197241, -0.01851078,  0.02347515,  0.1299994 ,
        0.06181602, -0.04789381, -0.03745378, -0.12499033, -0.08104145,
       -0.12535763,  0.05842031,  0.00841246,  0.05944181, -0.0181949 ,
        0.05583062, -0.02722489,  0.0944633 , -0.0735614 ,  0.0133223 ,
        0.08689121, -0.03171949,  0.05850742,  0.00937041, -0.10463272,
       -0.09268833, -0.08810611,  0.01258975, -0.0276544 , -0.09455128,
        0.04041737,  0.12387407, -0.13891677, -0.0192964 ,  0.03450453,
       -0.01434668,  0.00334137,  0.0757686 , -0.09515174,  0.02652472,
        0.09058916, -0.09689046, -0.05073312, -0.00858528,  0.03315858,
        0.03302471,  0.09037638,  0.10625027, -0.09187414,  0.05

In [117]:
def predict_prob(X,theta):    
    return sigmoid(np.dot(X,theta))
    
def predict(X,theta):
    return predict_prob(X,theta).round()

In [118]:

preds = predict(X,m1)
(preds == Y).mean()

0.9919293188796291

Creating one vs all model

In [120]:
i=0
list_of_model=[]


tagged_list=tagged_list[:3]

for t in tagged_list:
#     print(i,t)
    X,Y=set_labels(t)    
    X = np.asarray(X)
    Y = np.asarray(Y)
    m=logistic(X,Y)
    list_of_model.append(m)    
    i+=1
    print(i)

/home/sathis/.local/lib/python3.5/site-packages/ipykernel_launcher.py:12: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if sys.path[0] == '':
/home/sathis/.local/lib/python3.5/site-packages/ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


In [125]:
len(list_of_model)

X[0]

array([ 0.15916301,  1.6339594 ,  1.5020187 , -0.8859577 , -0.4248019 ,
        0.2190207 , -1.213853  , -0.26153135, -0.38434863,  0.7170494 ,
        0.31501803,  0.19456813,  0.06541097,  0.7194808 ,  0.8512847 ,
        1.4106065 ,  1.9549584 ,  0.42091617, -0.28043222, -0.337628  ,
       -0.44907588,  1.5165097 ,  0.2141224 , -0.27610213, -1.5047    ,
       -0.7066438 ,  0.5463149 ,  0.43357623,  1.432402  ,  0.9231266 ,
        1.4457808 , -0.67904705, -0.09708947, -0.67605364,  0.20409805,
       -0.63440734,  0.3109709 , -1.0896271 ,  0.8434325 , -0.15642618,
       -1.0061816 ,  0.36208808, -0.67997277, -0.10551537,  1.203434  ,
        1.07059   ,  1.0199058 , -0.14729822,  0.31282827,  1.0853956 ,
       -0.48083252, -1.4153005 ,  1.6024846 ,  0.22166537, -0.39776775,
        0.16438764, -0.04245919, -0.86300254,  1.0866425 , -0.31002873,
       -1.0420072 ,  1.1140199 ,  0.58618987,  0.10296959, -0.37997308,
       -0.377939  , -1.0374603 , -1.2127775 ,  1.0603414 , -0.65

In [151]:

i=0
for m in list_of_model:
    preds = predict(X,m)
    a=(preds == Y).mean()
    print(tagged_list[i],a)
    i+=1
    
    

CD-HL 0.9945735948367692
NR-HL 0.9945735948367692
HVZ 0.9945735948367692


In [130]:
# list_of_model[0]

array([-0.01558606, -0.15591241, -0.14347647,  0.08422861,  0.04104375,
       -0.02107251,  0.11544738,  0.02525268,  0.03643361, -0.06829607,
       -0.03049497, -0.01870151, -0.00645748, -0.06925587, -0.08194224,
       -0.1342714 , -0.18615963, -0.03978845,  0.02647112,  0.03225507,
        0.04294609, -0.14478287, -0.02028107,  0.02576746,  0.14258147,
        0.06783576, -0.0525803 , -0.04112634, -0.13698513, -0.08893065,
       -0.13751993,  0.06416672,  0.00937443,  0.06506199, -0.0199872 ,
        0.06121564, -0.02980908,  0.10373997, -0.08069145,  0.01465044,
        0.09527463, -0.03469723,  0.06411822,  0.01035605, -0.11478673,
       -0.10166932, -0.09664239,  0.01369215, -0.03036438, -0.10359691,
        0.04439752,  0.13580604, -0.15238811, -0.02122345,  0.0377618 ,
       -0.01571364,  0.00359297,  0.08306177, -0.1044142 ,  0.02920371,
        0.09930944, -0.10630466, -0.05563959, -0.00941889,  0.0363714 ,
        0.03622754,  0.09912169,  0.11656997, -0.10085772,  0.06

In [131]:
# list_of_model[1]

array([-0.0156092 , -0.15611381, -0.14365713,  0.08433859,  0.0410974 ,
       -0.02110035,  0.11559681,  0.02528384,  0.03648284, -0.06838298,
       -0.03053386, -0.01872349, -0.00646319, -0.06934472, -0.08204413,
       -0.13444396, -0.18639626, -0.03984102,  0.02650359,  0.03229457,
        0.04300281, -0.14496802, -0.02030777,  0.02579952,  0.14276489,
        0.06792123, -0.05264642, -0.04117954, -0.13715952, -0.08904269,
       -0.13769602,  0.06424806,  0.00938608,  0.06514802, -0.0200151 ,
        0.06129464, -0.02984672,  0.10386916, -0.08079533,  0.01466719,
        0.09539759, -0.03474118,  0.06420152,  0.01037073, -0.11493379,
       -0.10180061, -0.09676568,  0.01371225, -0.0304019 , -0.10373183,
        0.04445383,  0.13597888, -0.15258298, -0.02124902,  0.03781199,
       -0.01573576,  0.0035986 ,  0.08316658, -0.10454596,  0.02923982,
        0.09943825, -0.10643998, -0.05570998, -0.00943209,  0.03641903,
        0.03627488,  0.09924827,  0.11671683, -0.10098582,  0.06

In [141]:
test_sents[0][0][0]

'RB'

In [142]:
# train_sents[0][1]
token_tag_pair_test=[]
for sentence in test_sents:
#     print(sentence)
    for ttu in sentence:
#         print(ttu)
        token_tag_pair_test.append(ttu)

In [152]:
def set_labels_test(label):
    X=[]
    Y=[]
    for ttp in token_tag_pair_test:
#         print(t[1])
        if(ttp[1]==label):
#             print(ttp)
            X.append(model[ttp[0]])
            Y.append(1);
        else:
#             X.append(ttp[0])
            X.append(model[ttp[0]])
            Y.append(0);
    
    return X,Y

In [155]:


def find_model(X,Y):
    i=0
    for m in list_of_model:
        preds = predict(X,m)
        a=(preds == Y).mean()
        print(tagged_list[i],a)
        i+=1

In [156]:





for t in tagged_list:
    X,Y=set_labels_test(t)    
    X = np.asarray(X)
    Y = np.asarray(Y)
    find_model(X,Y)
    
    
    

/home/sathis/.local/lib/python3.5/site-packages/ipykernel_launcher.py:12: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if sys.path[0] == '':
/home/sathis/.local/lib/python3.5/site-packages/ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


CD-HL 0.9954236716604846
NR-HL 0.9954236716604846
HVZ 0.9954236716604846
CD-HL 0.9955681872922588
NR-HL 0.9955681872922588
HVZ 0.9955681872922588
CD-HL 0.9929669059203237
NR-HL 0.9929669059203237
HVZ 0.9929669059203237
